name: Build ReleaseDebug

on:
  workflow_dispatch:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/just_build.yml
    with:
      sign: true
      debug: true
    secrets: inherit
